#-------------------------------------------------------------------------------------------------------------
# Copyright (c) 2016 Loïc Guibert <lfdummy-devel@yahoo.fr>
#-------------------------------------------------------------------------------------------------------------
# This file is part of docker-utils.
#
# docker-utils is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#-------------------------------------------------------------------------------------------------------------
# Object : Sample Dockerfile to use with the 'docker-build-image' script
#-------------------------------------------------------------------------------------------------------------


#-------------------------------------------------------------------------------------------------------------
FROM hello-world


#-------------------------------------------------------------------------------------------------------------
# Write your Dockerfile command line here...


#-------------------------------------------------------------------------------------------------------------
MAINTAINER Loïc Guibert "lfdummy-devel@yahoo.fr"

LABEL \
    image_name="examples/my_image" \
    version="2016-02-24"
